BPS/BPS/Models/Engineer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace BPS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    
    public partial class Engineer
    {
        [Required]
        [Display(Name = "User Name")]
        [StringLength(15, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 4)]
        [Remote("UserNameExist", "User", ErrorMessage = "Sorry, This User Name Already Exist")]
        public string UserName { get; set; }
        [Required]
        [StringLength(15, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [System.ComponentModel.DataAnnotations.Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string RePassword { get; set; }


        public int id { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [MinLength(3, ErrorMessage = "Minimum 3 Leter")]
        [Display(Name = "Engineer Name")]
        public string engName { get; set; }
        [RegularExpression(@"^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$", ErrorMessage = "Please enter a valid email")]
        [Required(ErrorMessage = "This Field is Required")]

        [Display(Name = "Engineer Email")]
        public string engEmail { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Contact Number")]
        public string engContact { get; set; }

        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "About")]
        public string engAbout { get; set; }
 
        [Display(Name = "Address")]
        public string engAdress { get; set; }
  
        [Display(Name = "Country")]
        public string engCountry { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Gender")]
        public string engGender { get; set; }
     
        [Display(Name = "Picture")]
        public byte[] engPicture{ get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Details")]
        public string engDetails { get; set; }
     
        [Display(Name = "Profile")]
        public string engProfile { get; set; }
        [Required(ErrorMessage = "This Field is Required")]
        [Display(Name = "Experience")]
        public string engExperience { get; set; }
        public string engEntryBy { get; set; }
        public Nullable<System.DateTime> engEntryDate { get; set; }
    }
}

BPS/BPS/Models/Engineers.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

BPS/BPS/Controllers/EngineerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BPS.BLL;
using BPS.Models;
using Microsoft.Ajax.Utilities;

namespace BPS.Controllers
{
	public class EngineerController : Controller
	{
		//
		// GET: /Engineer/
		[HttpGet]
		public ActionResult SaveEngInfo()
		{
			return View();
		}
        EngineerBLL AEngineerBll = new EngineerBLL();
		[HttpPost]
		public ActionResult SaveEngInfo(Engineer aEngineer)
		{
			
			ViewBag.Message = AEngineerBll.SaveEngProfile(aEngineer);
			return View();
		}

		public ActionResult EngineerViewProfile()
		{
		    List<Engineer> EngineerProfile = AEngineerBll.EngineersViewProfile();
            return View(EngineerProfile);
		}
	}
}

BPS/BPS/Views/Engineer/EngineerViewProfile.cshtml
@model List<BPS.Models.Engineer>
@{
    ViewBag.Title = "EngineerViewProfile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EngineerViewProfile</h2>


<div class="wrapper row3">
    <main class="hoc container clear">
        <!-- main body -->
        <!-- ################################################################################################ -->
<div class="content three_quarter first">
    <!-- ################################################################################################ -->

    <br><br>

    @Html.ActionLink("Add Engineer Profile", "SaveEngInfo", "Engineer") <br><br>
    <div class="linear-tiles-wrapper">
        <div class="blog-post">
            @{
        foreach (var data in Model)
        {


            <h1> @data.engName</h1>
                <header>
                    <figure class="avatar"><img src="../images/ashique.png" alt=""></figure>
                    <address>
                        @data.engCountry <a href="#">@data.engEmail </a>||<a href=""> Building Estimation</a>
                    </address>
                    <h3>Structural Engineer, Estimator & CAD Drafter</h3>
                    <i class="fa fa-phone" aria-hidden="true"><span>&nbsp;&nbsp;@data.engContact</span></i>
                </header>

                <p style="text-align: justify;">
                    @data.engDetails
                        <br>
                </p>
            <button type="submit" class="btn btn-primary btn-submit btn-Expand" id="show">Expand Profile</button>

    <div id="ShowProfile" class="ShowProfile">

        <p style="text-align: justify;">
            @data.engAbout
        </p>
        <p style="text-align: justify;">
            @data.engAdress
        </p>
        <label hidden>@data.id</label>
        <br>
    </div>



        }
    <hr>
        }
</div>   
           
        
        
                
            

    <div>
        <h5 class="text-right">Last updated: Nov 16, 2019</h5>
    </div>
</div>
    </main>
    </div>



            <!-- ################################################################################################ -->
            <!-- / main body -->
            <div class="clear"></div>

             @Scripts.Render("~/bundles/bootstrap")



            @Scripts.Render("~/bundles/jquery")
            @section scripts
            {

                <script src="~/Scripts/jquery-3.3.1.js"></script>

                <script src="~/Scripts/jquery.dataTables.min.js"></script>
                <script>
                    var hideleng=false;
                    $(document).ready(function () {
                        $('#dataTable').DataTable({

                            "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                            "pagingType": "full_numbers"
                        });
                        $("#ShowProfile").hide();
                        $(".ShowProfile").hide();
                        $("#show").click(function () {
                            $(".ShowProfile").show();
                        });
                    });




                 </script>
        }

BPS/BPS/Views/Engineer/SaveEngInfo.cshtml
@using BPS.Models
@model BPS.Models.Engineer

@{
    ViewBag.Title = "SaveEngInfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

<div class="headingStyle">
    <span class="top right"></span>
    <span class="top left"></span>
    <h2 class="text-center">Engineer Profile Registration Form</h2>
    <span class="bottom right"></span>
    <span class="bottom left"></span>
</div>
<div class="login-form">
    <form  method="POST" class="wow slideInDown" data-wow-duration="2s" data-wow-offset="0">

        

        <div class="form-horizontal">
           
            <hr />
            @Html.ValidationSummary(true)
            <!--------------Client User Create---------------------->
            <div class="row from-group">
                <h3 class="text-primary">Engineer Account Information</h3>
            </div>
            <div class="row from group">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.UserName)
                    @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserName)
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.Password)
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Password)
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.RePassword)
                    @Html.PasswordFor(model => model.RePassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RePassword)
                </div>
            </div>
            <hr />

            <!--------------------------------------------------Details Engineer----------------------------------------------------->
            <div class="row from-group">
                <h3 class="text-primary">Engineer Details Information</h3>
            </div>
            <!---name--->
            <div class="row form-group">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.engName)
                    @Html.TextBoxFor(model => model.engName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.engName)
                </div>
    
            <!---Email--->
                <div class="col-md-4">

                    @Html.LabelFor(model => model.engEmail)
                    @Html.TextBoxFor(model => model.engEmail, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.engEmail)
                </div>
                
                <!---Contact--->
                   <div class="col-md-4">
                        @Html.LabelFor(model => model.engContact)
                        @Html.TextBoxFor(model => model.engContact, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.engContact)
                    </div>
             </div>
                    <!---About--->
            <!-------------------------------------------------2nd Row---------------------------------->
            <div class="form-group row">
                <div class="col-md-4">
                    @Html.LabelFor(model => model.engGender)

                    Male
                    @Html.RadioButtonFor(model => model.engGender, "Male")
                    Female
                    @Html.RadioButtonFor(model => model.engGender, "Female")
                    @Html.ValidationMessageFor(model => model.engGender)
                </div>
                <div class="col-md-4">
                    @Html.LabelFor(model => model.engExperience)
                    @Html.TextBoxFor(model => model.engExperience, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.engExperience)
                </div>
                   <!---Country--->
             
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.engCountry)
                        @Html.TextBoxFor(model => model.engCountry, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.engCountry)
                    </div>
           </div>
                <!---Gender--->
            <!-------------------------------------------------2nd Row---------------------------------->
                <div class="form-group row">
                    
                    
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.engAbout)
                        @Html.TextAreaFor(model => model.engAbout, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.engAbout)
                    </div>

                    <!---Adress--->

                    <div class="col-md-4">
                        @Html.LabelFor(model => model.engAdress)
                        @Html.TextAreaFor(model => model.engAdress, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.engAdress)
                    </div>
                    

                @*<div class="form-group">
                @Html(model => model.engPicture, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.engPicture)
                    @Html.ValidationMessageFor(model => model.engPicture)
                </div>
            </div>*@
                <!---Details--->
               
                    <div class="col-md-4">
                        @Html.LabelFor(model => model.engDetails)
                
                        @Html.TextAreaFor(model => model.engDetails, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.engDetails)
                    </div>
               

                <!---Experience--->
                   
                </div>



            <div class="form-group row">
                <div class="col-md-4 text-right"></div>
                <div class=" col-md-2 text-right ">
                    <br />
                    <input type="submit" value="Create Account" class="btn btn-default btn-primary" style="width:300px;" />
                </div>
                <label class="label label-success">@ViewBag.Message</label>
            </div>
            </div>


</form>
</div>
    
    <div>
        @Html.ActionLink("Back to Home Page", "Index", "Home")
    </div>